spring:
  application:
    name: novice-email #服务名称
  datasource:
    url: jdbc:mysql://192.168.152.128:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 5
    host: 192.168.152.128
    port: 6379
    password:
  messages:
    basename: message/messages  #国际化配置
    encoding: UTF-8
  mail:
    host: smtp.sina.com
    username: catcoder@sina.com
    password: 19971128lv
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.univer.*.po